spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

server:
  port: 8084


okta:
  oauth2:
    audience: api://default
    issuer: https://dev-51144467.okta.com/oauth2/default
    client-id: 0oaa615eho8hsHfHK5d7
    client-secret: ksrFn7561lxiUjBHt5RtaCTSAb7BPWgpazkRgqm0
    scopes: openid, profile, email, offline_access



