server:
  port: 8083

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kartik1502/microservices-config
          clone-on-start: true