server:
  port: 8082

spring:
  application:
    name: RATING-SERVICE
    bad_request: 403
    responseCode: 200
    conflict: 409
    not_found: 404

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_rating_rating_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  config:
    import: configserver:http://localhost:8083

logging:
  level:
    web: debug
    org.springframework.web: info
    org.training: error

  logback:
    rollingpolicy:
      max-file-size: 1MB

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      userHotelRetry:
        max-attempts: 3
        wait-duration: 3s

  ratelimiter:
    instances:
      userHotelRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s